name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test

    - name: Build
      run: |
        commit=`git rev-parse --short HEAD`
        built_at=`date +%FT%T%z`
        GOOS=darwin GOARCH=amd64 go build -o sd-ingest_amd64 -ldflags "-X main.commit=${commit} -X main.builtAt='${built_at}'" 
        GOOS=darwin GOARCH=arm64 go build -o sd-ingest_arm64 -ldflags "-X main.commit=${commit} -X main.builtAt='${built_at}'" 

    - name: 'AMD 64 Build'
      uses: actions/upload-artifact@v3
      with:
        name: sd-ingest_amd64
        path: ./sd-ingest_amd64
    - name: 'ARM 64 Build'
      uses: actions/upload-artifact@v3
      with:
        name: sd-ingest_arm64
        path: ./sd-ingest_arm64
